
server:
  port: 8083

spring:
  application:
    name: server-c
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
  zipkin:
    base-url: http://localhost:9411/ # 指定了Zipkin服务器的地址